config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "orders#index"
  
  get '/reports', to: 'reports#index', as: 'reports'
  resources :menu_items
  resources :orders, only: [:index, :new, :edit, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :menu_categories
  has_many :menu_items, through: :menu_categories
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :menu_item
  belongs_to :category
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
  validates :description, length: { maximum: 150 }
  validates :categories, presence: true

  has_many :menu_categories
  has_many :categories, through: :menu_categories

  def category_names
    self.categories.map{ |category| category.name }.join(", ")
  end

  def category_names=(new_categories)
    category_names = new_categories.split(",").map(&:strip) 

    categories = []
    category_names.each do |category_name|
      categories << Category.find_or_create_by(name: category_name)
    end

    self.categories = categories.uniq
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :status, inclusion: { in: %w[NEW PAID CANCELED] }
  validates :email, email: true
  
  has_many :order_details
  has_many :menu_items, through: :order_details

  accepts_nested_attributes_for :order_details, allow_destroy: true

  before_save :calculate_total_price

  private

  def calculate_total_price
    total_price = self.order_details.sum do |order_detail| 
      order_detail.save
      order_detail.price * order_detail.quantity 
    end
    
    self.total_price = total_price
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item

  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  before_save :save_price

  private

  def save_price
    self.price = self.menu_item.price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.all
  end
  
  def show
    @menu_item = MenuItem.find(params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      redirect_to @menu_item
    else
      render :new
    end
  end

  def update
    @menu_item = MenuItem.find(params[:id])
    
    if @menu_item.update(menu_item_params)
      redirect_to @menu_item
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy

    redirect_to menu_items_url
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :price, :category_names)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.order(created_at: :desc)
  end
  
  def new
    @order = Order.new
    
    add_items_count = 1
    if params[:count]
      if params[:count].to_i > 0
        add_items_count = params[:count].to_i
      end
    end
    
    add_items_count.times { @order.order_details.build }
  end

  def edit
    @order = Order.find(params[:id])
    if params[:count]
      add_items_count = params[:count].to_i
      if add_items_count > 0
        add_items_count.times { @order.order_details.build }
      end
    end
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to orders_url
    else
      render :new
    end
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to orders_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_url
  end

  private

  def order_params
    params.require(:order).permit(:status, :email, order_details_attributes: [ :id, :menu_item_id, :quantity, :_destroy ])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    if params[:date]
      @orders = Order.where(status: 'PAID', created_at: params[:date].to_date.all_day)
      @date = params[:date]
    else
      @orders = Order.where(status: 'PAID', created_at: Date.today.all_day)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_navbar.html.erb
<table style="border: 1px solid black ; table-layout: fixed ; width: 100%;">
  <tr>
    <th><%= link_to "Reports", reports_path %></th>
    <th><%= link_to "Orders", orders_path %></th>
    <th><%= link_to "Menu", menu_items_path %> </th>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %> 
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item) do |form| %>
  <% if menu_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, step: 500 %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :category_names, style: "display: block" %>
    <%= form.text_area :category_names %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div id="<%= dom_id menu_item %>">
  <p>
    <strong>Name:</strong>
    <%= menu_item.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu_item.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu_item.description %>
  </p>

  <p>
    <strong>Categories:</strong>
    <%= menu_item.category_names %>
  </p>

</div>

app/views/menu_items/edit.html.erb
<h1>Editing menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Show this menu item", @menu_item %> |
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "New menu item", new_menu_item_path %>

<h1>Menu items</h1>

<div id="menu_items">
  <% @menu_items.each do |menu_item| %>
    <hr>
    <%= render menu_item %>
    <p>
      <%= link_to "Show this menu item", menu_item %>
    </p>
  <% end %>
</div>

app/views/menu_items/new.html.erb
<h1>New menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_item %>

<div>
  <%= link_to "Edit this menu item", edit_menu_item_path(@menu_item) %> |
  <%= link_to "Back to menu items", menu_items_path %>

  <%= button_to "Destroy this menu item", @menu_item, method: :delete %>
</div>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, %w[NEW PAID CANCELED] %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <br>
    <%= form.label :items, style: "display: block" %>
    <%= form.fields_for :order_details do |details_form| %>
      <%= details_form.collection_select :menu_item_id, MenuItem.all, :id, :name %>
      <%= details_form.number_field :quantity %>
      <%= details_form.check_box :_destroy %>
      remove?
      <br>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
      
<br>
<%= form_with(url: action, method: :get) do |items_form| %>
  <%= items_form.label :add %>
  <%= items_form.number_field :count %>Items
  <%= items_form.submit "Go" %>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Date:</strong>
    <%= order.created_at.to_date.to_fs(:rfc822) %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <% case order.status %>
    <% when "PAID" %>
      <% status_color = "green" %>
    <% when "CANCELED" %>
      <% status_color = "red" %>
    <% else %>
      <% status_color = "blue" %>
    <% end %>
    <span style="color:<%= status_color %>"><%= order.status %></span>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= order.email %>
  </p>

  <table border="1px solid black">
    <tr>
      <th width="100">Item</th>
      <th width="100">Price</th>
      <th width="100">Quantity</th>
    </tr>
    <% order.order_details.each do |order_detail| %>
      <tr>
        <td>
          <%= order_detail.menu_item.name %>
        </td>
        <td>
          <%= "Rp#{number_with_delimiter(order_detail.price)}" %>
        </td>
        <td>
          <%= order_detail.quantity %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <p>
    <strong>Total:</strong>
    <%= order.total_price %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order, action: "/orders/#{@order.id}/edit" %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "New order", new_order_path %>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <hr>
    <%= render order %>
    <div>
      <%= link_to "Edit this order", edit_order_path(order) %>
      <%= button_to "Destroy this order", order, method: :delete %>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order, action: "/orders/new" %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/reports/index.html.erb
<h1>Reports</h1>
<% @date = Date.today unless defined?(@date) %>
<%= form_with url: reports_path, method: :get do |form| %>
  <%= form.label :date %>
  <%= form.date_field :date, value: @date %>
  <%= form.submit "Go" %>
<% end %>
<% if @orders.empty? %>
  No paid orders found
<% else %>
  <% total_income = @orders.pluck(:total_price).sum %>
  <h3>Total Income = <%= "Rp#{number_with_delimiter(total_income)}" %></h3>
  <div id="reports">
    <% @orders.each do |order| %>
      <hr>
      <%= render order %>
    <% end %>
  </div>
<% end %>